/*
 * AWS Account
 * Operations for Amazon Web Services Account Management
 *
 * The version of the OpenAPI document: 2021-02-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DeleteAlternateContactRequest
 */
public class DeleteAlternateContactRequestTest {
    private final DeleteAlternateContactRequest model = new DeleteAlternateContactRequest();

    /**
     * Model tests for DeleteAlternateContactRequest
     */
    @Test
    public void testDeleteAlternateContactRequest() {
        // TODO: test DeleteAlternateContactRequest
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'alternateContactType'
     */
    @Test
    public void alternateContactTypeTest() {
        // TODO: test alternateContactType
    }

}
