/*
 * AWS Account
 * Operations for Amazon Web Services Account Management
 *
 * The version of the OpenAPI document: 2021-02-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.GetAlternateContactResponseAlternateContact;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetAlternateContactResponse
 */
public class GetAlternateContactResponseTest {
    private final GetAlternateContactResponse model = new GetAlternateContactResponse();

    /**
     * Model tests for GetAlternateContactResponse
     */
    @Test
    public void testGetAlternateContactResponse() {
        // TODO: test GetAlternateContactResponse
    }

    /**
     * Test the property 'alternateContact'
     */
    @Test
    public void alternateContactTest() {
        // TODO: test alternateContact
    }

}
