/*
 * AWS Account
 * Operations for Amazon Web Services Account Management
 *
 * The version of the OpenAPI document: 2021-02-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.RegionOptStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListRegionsRequest
 */
public class ListRegionsRequestTest {
    private final ListRegionsRequest model = new ListRegionsRequest();

    /**
     * Model tests for ListRegionsRequest
     */
    @Test
    public void testListRegionsRequest() {
        // TODO: test ListRegionsRequest
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'maxResults'
     */
    @Test
    public void maxResultsTest() {
        // TODO: test maxResults
    }

    /**
     * Test the property 'nextToken'
     */
    @Test
    public void nextTokenTest() {
        // TODO: test nextToken
    }

    /**
     * Test the property 'regionOptStatusContains'
     */
    @Test
    public void regionOptStatusContainsTest() {
        // TODO: test regionOptStatusContains
    }

}
