/*
 * AWS Account
 * Operations for Amazon Web Services Account Management
 *
 * The version of the OpenAPI document: 2021-02-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets AlternateContactType
 */
@JsonAdapter(AlternateContactType.Adapter.class)
public enum AlternateContactType {
  
  BILLING("BILLING"),
  
  OPERATIONS("OPERATIONS"),
  
  SECURITY("SECURITY");

  private String value;

  AlternateContactType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AlternateContactType fromValue(String value) {
    for (AlternateContactType b : AlternateContactType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<AlternateContactType> {
    @Override
    public void write(final JsonWriter jsonWriter, final AlternateContactType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AlternateContactType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AlternateContactType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    AlternateContactType.fromValue(value);
  }
}

