/*
 * AWS Account
 * Operations for Amazon Web Services Account Management
 *
 * The version of the OpenAPI document: 2021-02-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * DeleteAlternateContactRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:03:31.192600+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class DeleteAlternateContactRequest {
  public static final String SERIALIZED_NAME_ACCOUNT_ID = "AccountId";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_ID)
  @javax.annotation.Nullable
  private String accountId;

  /**
   * Specifies which of the alternate contacts to delete. 
   */
  @JsonAdapter(AlternateContactTypeEnum.Adapter.class)
  public enum AlternateContactTypeEnum {
    BILLING("BILLING"),
    
    OPERATIONS("OPERATIONS"),
    
    SECURITY("SECURITY");

    private String value;

    AlternateContactTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AlternateContactTypeEnum fromValue(String value) {
      for (AlternateContactTypeEnum b : AlternateContactTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<AlternateContactTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AlternateContactTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AlternateContactTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return AlternateContactTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      AlternateContactTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_ALTERNATE_CONTACT_TYPE = "AlternateContactType";
  @SerializedName(SERIALIZED_NAME_ALTERNATE_CONTACT_TYPE)
  @javax.annotation.Nonnull
  private AlternateContactTypeEnum alternateContactType;

  public DeleteAlternateContactRequest() {
  }

  public DeleteAlternateContactRequest accountId(@javax.annotation.Nullable String accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * &lt;p&gt;Specifies the 12 digit account ID number of the Amazon Web Services account that you want to access or modify with this operation.&lt;/p&gt; &lt;p&gt;If you do not specify this parameter, it defaults to the Amazon Web Services account of the identity used to call the operation.&lt;/p&gt; &lt;p&gt;To use this parameter, the caller must be an identity in the &lt;a href&#x3D;\&quot;https://docs.aws.amazon.com/organizations/latest/userguide/orgs_getting-started_concepts.html#account\&quot;&gt;organization&#39;s management account&lt;/a&gt; or a delegated administrator account, and the specified account ID must be a member account in the same organization. The organization must have &lt;a href&#x3D;\&quot;https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_org_support-all-features.html\&quot;&gt;all features enabled&lt;/a&gt;, and the organization must have &lt;a href&#x3D;\&quot;https://docs.aws.amazon.com/organizations/latest/userguide/using-orgs-trusted-access.html\&quot;&gt;trusted access&lt;/a&gt; enabled for the Account Management service, and optionally a &lt;a href&#x3D;\&quot;https://docs.aws.amazon.com/organizations/latest/userguide/using-orgs-delegated-admin.html\&quot;&gt;delegated admin&lt;/a&gt; account assigned.&lt;/p&gt; &lt;note&gt; &lt;p&gt;The management account can&#39;t specify its own &lt;code&gt;AccountId&lt;/code&gt;; it must call the operation in standalone context by not including the &lt;code&gt;AccountId&lt;/code&gt; parameter.&lt;/p&gt; &lt;/note&gt; &lt;p&gt;To call this operation on an account that is not a member of an organization, then don&#39;t specify this parameter, and call the operation using an identity belonging to the account whose contacts you wish to retrieve or modify.&lt;/p&gt;
   * @return accountId
   */
  @javax.annotation.Nullable
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(@javax.annotation.Nullable String accountId) {
    this.accountId = accountId;
  }


  public DeleteAlternateContactRequest alternateContactType(@javax.annotation.Nonnull AlternateContactTypeEnum alternateContactType) {
    this.alternateContactType = alternateContactType;
    return this;
  }

  /**
   * Specifies which of the alternate contacts to delete. 
   * @return alternateContactType
   */
  @javax.annotation.Nonnull
  public AlternateContactTypeEnum getAlternateContactType() {
    return alternateContactType;
  }

  public void setAlternateContactType(@javax.annotation.Nonnull AlternateContactTypeEnum alternateContactType) {
    this.alternateContactType = alternateContactType;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteAlternateContactRequest deleteAlternateContactRequest = (DeleteAlternateContactRequest) o;
    return Objects.equals(this.accountId, deleteAlternateContactRequest.accountId) &&
        Objects.equals(this.alternateContactType, deleteAlternateContactRequest.alternateContactType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, alternateContactType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteAlternateContactRequest {\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    alternateContactType: ").append(toIndentedString(alternateContactType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("AccountId");
    openapiFields.add("AlternateContactType");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("AlternateContactType");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DeleteAlternateContactRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DeleteAlternateContactRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DeleteAlternateContactRequest is not found in the empty JSON string", DeleteAlternateContactRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DeleteAlternateContactRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DeleteAlternateContactRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DeleteAlternateContactRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("AccountId") != null && !jsonObj.get("AccountId").isJsonNull()) && !jsonObj.get("AccountId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `AccountId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("AccountId").toString()));
      }
      if (!jsonObj.get("AlternateContactType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `AlternateContactType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("AlternateContactType").toString()));
      }
      // validate the required field `AlternateContactType`
      AlternateContactTypeEnum.validateJsonElement(jsonObj.get("AlternateContactType"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DeleteAlternateContactRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DeleteAlternateContactRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DeleteAlternateContactRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DeleteAlternateContactRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<DeleteAlternateContactRequest>() {
           @Override
           public void write(JsonWriter out, DeleteAlternateContactRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DeleteAlternateContactRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DeleteAlternateContactRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DeleteAlternateContactRequest
   * @throws IOException if the JSON string is invalid with respect to DeleteAlternateContactRequest
   */
  public static DeleteAlternateContactRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DeleteAlternateContactRequest.class);
  }

  /**
   * Convert an instance of DeleteAlternateContactRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

