/*
 * AWS Account
 * Operations for Amazon Web Services Account Management
 *
 * The version of the OpenAPI document: 2021-02-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.AlternateContactType;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * GetAlternateContactResponseAlternateContact
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:03:31.192600+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class GetAlternateContactResponseAlternateContact {
  public static final String SERIALIZED_NAME_ALTERNATE_CONTACT_TYPE = "AlternateContactType";
  @SerializedName(SERIALIZED_NAME_ALTERNATE_CONTACT_TYPE)
  @javax.annotation.Nullable
  private AlternateContactType alternateContactType;

  public static final String SERIALIZED_NAME_EMAIL_ADDRESS = "EmailAddress";
  @SerializedName(SERIALIZED_NAME_EMAIL_ADDRESS)
  @javax.annotation.Nullable
  private String emailAddress;

  public static final String SERIALIZED_NAME_NAME = "Name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_PHONE_NUMBER = "PhoneNumber";
  @SerializedName(SERIALIZED_NAME_PHONE_NUMBER)
  @javax.annotation.Nullable
  private String phoneNumber;

  public static final String SERIALIZED_NAME_TITLE = "Title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  @javax.annotation.Nullable
  private String title;

  public GetAlternateContactResponseAlternateContact() {
  }

  public GetAlternateContactResponseAlternateContact alternateContactType(@javax.annotation.Nullable AlternateContactType alternateContactType) {
    this.alternateContactType = alternateContactType;
    return this;
  }

  /**
   * Get alternateContactType
   * @return alternateContactType
   */
  @javax.annotation.Nullable
  public AlternateContactType getAlternateContactType() {
    return alternateContactType;
  }

  public void setAlternateContactType(@javax.annotation.Nullable AlternateContactType alternateContactType) {
    this.alternateContactType = alternateContactType;
  }


  public GetAlternateContactResponseAlternateContact emailAddress(@javax.annotation.Nullable String emailAddress) {
    this.emailAddress = emailAddress;
    return this;
  }

  /**
   * Get emailAddress
   * @return emailAddress
   */
  @javax.annotation.Nullable
  public String getEmailAddress() {
    return emailAddress;
  }

  public void setEmailAddress(@javax.annotation.Nullable String emailAddress) {
    this.emailAddress = emailAddress;
  }


  public GetAlternateContactResponseAlternateContact name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public GetAlternateContactResponseAlternateContact phoneNumber(@javax.annotation.Nullable String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

  /**
   * Get phoneNumber
   * @return phoneNumber
   */
  @javax.annotation.Nullable
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(@javax.annotation.Nullable String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }


  public GetAlternateContactResponseAlternateContact title(@javax.annotation.Nullable String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @javax.annotation.Nullable
  public String getTitle() {
    return title;
  }

  public void setTitle(@javax.annotation.Nullable String title) {
    this.title = title;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAlternateContactResponseAlternateContact getAlternateContactResponseAlternateContact = (GetAlternateContactResponseAlternateContact) o;
    return Objects.equals(this.alternateContactType, getAlternateContactResponseAlternateContact.alternateContactType) &&
        Objects.equals(this.emailAddress, getAlternateContactResponseAlternateContact.emailAddress) &&
        Objects.equals(this.name, getAlternateContactResponseAlternateContact.name) &&
        Objects.equals(this.phoneNumber, getAlternateContactResponseAlternateContact.phoneNumber) &&
        Objects.equals(this.title, getAlternateContactResponseAlternateContact.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alternateContactType, emailAddress, name, phoneNumber, title);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAlternateContactResponseAlternateContact {\n");
    sb.append("    alternateContactType: ").append(toIndentedString(alternateContactType)).append("\n");
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("AlternateContactType");
    openapiFields.add("EmailAddress");
    openapiFields.add("Name");
    openapiFields.add("PhoneNumber");
    openapiFields.add("Title");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetAlternateContactResponseAlternateContact
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetAlternateContactResponseAlternateContact.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetAlternateContactResponseAlternateContact is not found in the empty JSON string", GetAlternateContactResponseAlternateContact.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetAlternateContactResponseAlternateContact.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetAlternateContactResponseAlternateContact` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `AlternateContactType`
      if (jsonObj.get("AlternateContactType") != null && !jsonObj.get("AlternateContactType").isJsonNull()) {
        AlternateContactType.validateJsonElement(jsonObj.get("AlternateContactType"));
      }
      // validate the optional field `EmailAddress`
      if (jsonObj.get("EmailAddress") != null && !jsonObj.get("EmailAddress").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("EmailAddress"));
      }
      // validate the optional field `Name`
      if (jsonObj.get("Name") != null && !jsonObj.get("Name").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("Name"));
      }
      // validate the optional field `PhoneNumber`
      if (jsonObj.get("PhoneNumber") != null && !jsonObj.get("PhoneNumber").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("PhoneNumber"));
      }
      // validate the optional field `Title`
      if (jsonObj.get("Title") != null && !jsonObj.get("Title").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("Title"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetAlternateContactResponseAlternateContact.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetAlternateContactResponseAlternateContact' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetAlternateContactResponseAlternateContact> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetAlternateContactResponseAlternateContact.class));

       return (TypeAdapter<T>) new TypeAdapter<GetAlternateContactResponseAlternateContact>() {
           @Override
           public void write(JsonWriter out, GetAlternateContactResponseAlternateContact value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetAlternateContactResponseAlternateContact read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetAlternateContactResponseAlternateContact given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetAlternateContactResponseAlternateContact
   * @throws IOException if the JSON string is invalid with respect to GetAlternateContactResponseAlternateContact
   */
  public static GetAlternateContactResponseAlternateContact fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetAlternateContactResponseAlternateContact.class);
  }

  /**
   * Convert an instance of GetAlternateContactResponseAlternateContact to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

