/*
 * AWS Account
 * Operations for Amazon Web Services Account Management
 *
 * The version of the OpenAPI document: 2021-02-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.RegionOptStatus;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * GetRegionOptStatusResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:03:31.192600+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class GetRegionOptStatusResponse {
  public static final String SERIALIZED_NAME_REGION_NAME = "RegionName";
  @SerializedName(SERIALIZED_NAME_REGION_NAME)
  @javax.annotation.Nullable
  private String regionName;

  public static final String SERIALIZED_NAME_REGION_OPT_STATUS = "RegionOptStatus";
  @SerializedName(SERIALIZED_NAME_REGION_OPT_STATUS)
  @javax.annotation.Nullable
  private RegionOptStatus regionOptStatus;

  public GetRegionOptStatusResponse() {
  }

  public GetRegionOptStatusResponse regionName(@javax.annotation.Nullable String regionName) {
    this.regionName = regionName;
    return this;
  }

  /**
   * Get regionName
   * @return regionName
   */
  @javax.annotation.Nullable
  public String getRegionName() {
    return regionName;
  }

  public void setRegionName(@javax.annotation.Nullable String regionName) {
    this.regionName = regionName;
  }


  public GetRegionOptStatusResponse regionOptStatus(@javax.annotation.Nullable RegionOptStatus regionOptStatus) {
    this.regionOptStatus = regionOptStatus;
    return this;
  }

  /**
   * Get regionOptStatus
   * @return regionOptStatus
   */
  @javax.annotation.Nullable
  public RegionOptStatus getRegionOptStatus() {
    return regionOptStatus;
  }

  public void setRegionOptStatus(@javax.annotation.Nullable RegionOptStatus regionOptStatus) {
    this.regionOptStatus = regionOptStatus;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetRegionOptStatusResponse getRegionOptStatusResponse = (GetRegionOptStatusResponse) o;
    return Objects.equals(this.regionName, getRegionOptStatusResponse.regionName) &&
        Objects.equals(this.regionOptStatus, getRegionOptStatusResponse.regionOptStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(regionName, regionOptStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetRegionOptStatusResponse {\n");
    sb.append("    regionName: ").append(toIndentedString(regionName)).append("\n");
    sb.append("    regionOptStatus: ").append(toIndentedString(regionOptStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("RegionName");
    openapiFields.add("RegionOptStatus");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetRegionOptStatusResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetRegionOptStatusResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetRegionOptStatusResponse is not found in the empty JSON string", GetRegionOptStatusResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetRegionOptStatusResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetRegionOptStatusResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `RegionName`
      if (jsonObj.get("RegionName") != null && !jsonObj.get("RegionName").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("RegionName"));
      }
      // validate the optional field `RegionOptStatus`
      if (jsonObj.get("RegionOptStatus") != null && !jsonObj.get("RegionOptStatus").isJsonNull()) {
        RegionOptStatus.validateJsonElement(jsonObj.get("RegionOptStatus"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetRegionOptStatusResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetRegionOptStatusResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetRegionOptStatusResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetRegionOptStatusResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<GetRegionOptStatusResponse>() {
           @Override
           public void write(JsonWriter out, GetRegionOptStatusResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetRegionOptStatusResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetRegionOptStatusResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetRegionOptStatusResponse
   * @throws IOException if the JSON string is invalid with respect to GetRegionOptStatusResponse
   */
  public static GetRegionOptStatusResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetRegionOptStatusResponse.class);
  }

  /**
   * Convert an instance of GetRegionOptStatusResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

