/*
 * AWS Account
 * Operations for Amazon Web Services Account Management
 *
 * The version of the OpenAPI document: 2021-02-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.RegionOptStatus;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ListRegionsRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:03:31.192600+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class ListRegionsRequest {
  public static final String SERIALIZED_NAME_ACCOUNT_ID = "AccountId";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_ID)
  @javax.annotation.Nullable
  private String accountId;

  public static final String SERIALIZED_NAME_MAX_RESULTS = "MaxResults";
  @SerializedName(SERIALIZED_NAME_MAX_RESULTS)
  @javax.annotation.Nullable
  private Integer maxResults;

  public static final String SERIALIZED_NAME_NEXT_TOKEN = "NextToken";
  @SerializedName(SERIALIZED_NAME_NEXT_TOKEN)
  @javax.annotation.Nullable
  private String nextToken;

  public static final String SERIALIZED_NAME_REGION_OPT_STATUS_CONTAINS = "RegionOptStatusContains";
  @SerializedName(SERIALIZED_NAME_REGION_OPT_STATUS_CONTAINS)
  @javax.annotation.Nullable
  private List<RegionOptStatus> regionOptStatusContains = new ArrayList<>();

  public ListRegionsRequest() {
  }

  public ListRegionsRequest accountId(@javax.annotation.Nullable String accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * &lt;p&gt;Specifies the 12-digit account ID number of the Amazon Web Services account that you want to access or modify with this operation. If you don&#39;t specify this parameter, it defaults to the Amazon Web Services account of the identity used to call the operation. To use this parameter, the caller must be an identity in the &lt;a href&#x3D;\&quot;https://docs.aws.amazon.com/organizations/latest/userguide/orgs_getting-started_concepts.html#account\&quot;&gt;organization&#39;s management account&lt;/a&gt; or a delegated administrator account. The specified account ID must also be a member account in the same organization. The organization must have &lt;a href&#x3D;\&quot;https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_org_support-all-features.html\&quot;&gt;all features enabled&lt;/a&gt;, and the organization must have &lt;a href&#x3D;\&quot;https://docs.aws.amazon.com/organizations/latest/userguide/using-orgs-trusted-access.html\&quot;&gt;trusted access&lt;/a&gt; enabled for the Account Management service, and optionally a &lt;a href&#x3D;\&quot;https://docs.aws.amazon.com/organizations/latest/userguide/using-orgs-delegated-admin.html\&quot;&gt;delegated admin&lt;/a&gt; account assigned.&lt;/p&gt; &lt;note&gt; &lt;p&gt;The management account can&#39;t specify its own &lt;code&gt;AccountId&lt;/code&gt;. It must call the operation in standalone context by not including the &lt;code&gt;AccountId&lt;/code&gt; parameter.&lt;/p&gt; &lt;/note&gt; &lt;p&gt;To call this operation on an account that is not a member of an organization, don&#39;t specify this parameter. Instead, call the operation using an identity belonging to the account whose contacts you wish to retrieve or modify.&lt;/p&gt;
   * @return accountId
   */
  @javax.annotation.Nullable
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(@javax.annotation.Nullable String accountId) {
    this.accountId = accountId;
  }


  public ListRegionsRequest maxResults(@javax.annotation.Nullable Integer maxResults) {
    this.maxResults = maxResults;
    return this;
  }

  /**
   * The total number of items to return in the command’s output. If the total number of items available is more than the value specified, a &lt;code&gt;NextToken&lt;/code&gt; is provided in the command’s output. To resume pagination, provide the &lt;code&gt;NextToken&lt;/code&gt; value in the &lt;code&gt;starting-token&lt;/code&gt; argument of a subsequent command. Do not use the &lt;code&gt;NextToken&lt;/code&gt; response element directly outside of the Amazon Web Services CLI. For usage examples, see &lt;a href&#x3D;\&quot;http://docs.aws.amazon.com/cli/latest/userguide/pagination.html\&quot;&gt;Pagination&lt;/a&gt; in the &lt;i&gt;Amazon Web Services Command Line Interface User Guide&lt;/i&gt;. 
   * minimum: 1
   * maximum: 50
   * @return maxResults
   */
  @javax.annotation.Nullable
  public Integer getMaxResults() {
    return maxResults;
  }

  public void setMaxResults(@javax.annotation.Nullable Integer maxResults) {
    this.maxResults = maxResults;
  }


  public ListRegionsRequest nextToken(@javax.annotation.Nullable String nextToken) {
    this.nextToken = nextToken;
    return this;
  }

  /**
   * A token used to specify where to start paginating. This is the &lt;code&gt;NextToken&lt;/code&gt; from a previously truncated response. For usage examples, see &lt;a href&#x3D;\&quot;http://docs.aws.amazon.com/cli/latest/userguide/pagination.html\&quot;&gt;Pagination&lt;/a&gt; in the &lt;i&gt;Amazon Web Services Command Line Interface User Guide&lt;/i&gt;.
   * @return nextToken
   */
  @javax.annotation.Nullable
  public String getNextToken() {
    return nextToken;
  }

  public void setNextToken(@javax.annotation.Nullable String nextToken) {
    this.nextToken = nextToken;
  }


  public ListRegionsRequest regionOptStatusContains(@javax.annotation.Nullable List<RegionOptStatus> regionOptStatusContains) {
    this.regionOptStatusContains = regionOptStatusContains;
    return this;
  }

  public ListRegionsRequest addRegionOptStatusContainsItem(RegionOptStatus regionOptStatusContainsItem) {
    if (this.regionOptStatusContains == null) {
      this.regionOptStatusContains = new ArrayList<>();
    }
    this.regionOptStatusContains.add(regionOptStatusContainsItem);
    return this;
  }

  /**
   * A list of Region statuses (Enabling, Enabled, Disabling, Disabled, Enabled_by_default) to use to filter the list of Regions for a given account. For example, passing in a value of ENABLING will only return a list of Regions with a Region status of ENABLING.
   * @return regionOptStatusContains
   */
  @javax.annotation.Nullable
  public List<RegionOptStatus> getRegionOptStatusContains() {
    return regionOptStatusContains;
  }

  public void setRegionOptStatusContains(@javax.annotation.Nullable List<RegionOptStatus> regionOptStatusContains) {
    this.regionOptStatusContains = regionOptStatusContains;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListRegionsRequest listRegionsRequest = (ListRegionsRequest) o;
    return Objects.equals(this.accountId, listRegionsRequest.accountId) &&
        Objects.equals(this.maxResults, listRegionsRequest.maxResults) &&
        Objects.equals(this.nextToken, listRegionsRequest.nextToken) &&
        Objects.equals(this.regionOptStatusContains, listRegionsRequest.regionOptStatusContains);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, maxResults, nextToken, regionOptStatusContains);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListRegionsRequest {\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    maxResults: ").append(toIndentedString(maxResults)).append("\n");
    sb.append("    nextToken: ").append(toIndentedString(nextToken)).append("\n");
    sb.append("    regionOptStatusContains: ").append(toIndentedString(regionOptStatusContains)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("AccountId");
    openapiFields.add("MaxResults");
    openapiFields.add("NextToken");
    openapiFields.add("RegionOptStatusContains");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ListRegionsRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ListRegionsRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ListRegionsRequest is not found in the empty JSON string", ListRegionsRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ListRegionsRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ListRegionsRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("AccountId") != null && !jsonObj.get("AccountId").isJsonNull()) && !jsonObj.get("AccountId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `AccountId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("AccountId").toString()));
      }
      if ((jsonObj.get("NextToken") != null && !jsonObj.get("NextToken").isJsonNull()) && !jsonObj.get("NextToken").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `NextToken` to be a primitive type in the JSON string but got `%s`", jsonObj.get("NextToken").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("RegionOptStatusContains") != null && !jsonObj.get("RegionOptStatusContains").isJsonNull() && !jsonObj.get("RegionOptStatusContains").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `RegionOptStatusContains` to be an array in the JSON string but got `%s`", jsonObj.get("RegionOptStatusContains").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ListRegionsRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ListRegionsRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ListRegionsRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ListRegionsRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<ListRegionsRequest>() {
           @Override
           public void write(JsonWriter out, ListRegionsRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ListRegionsRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ListRegionsRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ListRegionsRequest
   * @throws IOException if the JSON string is invalid with respect to ListRegionsRequest
   */
  public static ListRegionsRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ListRegionsRequest.class);
  }

  /**
   * Convert an instance of ListRegionsRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

