/*
 * AWS Account
 * Operations for Amazon Web Services Account Management
 *
 * The version of the OpenAPI document: 2021-02-01
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets RegionOptStatus
 */
@JsonAdapter(RegionOptStatus.Adapter.class)
public enum RegionOptStatus {
  
  ENABLED("ENABLED"),
  
  ENABLING("ENABLING"),
  
  DISABLING("DISABLING"),
  
  DISABLED("DISABLED"),
  
  ENABLED_BY_DEFAULT("ENABLED_BY_DEFAULT");

  private String value;

  RegionOptStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static RegionOptStatus fromValue(String value) {
    for (RegionOptStatus b : RegionOptStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<RegionOptStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final RegionOptStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public RegionOptStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return RegionOptStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    RegionOptStatus.fromValue(value);
  }
}

